# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" "uinput" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/0a4ce7e8-867e-4da2-87d1-d29134571f9e";
      fsType = "ext4";
      options = [ "defaults" "x-gvfs-show" ];
    };

  fileSystems."/mnt/games" =
    { device = "/dev/disk/by-uuid/649c5ccc-f498-41b6-b661-de1dd6acc219";
      fsType = "ext4";
      options = [ "defaults" "x-gvfs-show" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/59DD-6E9B";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/90008975-5bb7-49ef-a996-cb62f024d694"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
